### ISSUE TITLE
not compiling in overleaf

### ISSUE THREAD

**Issue by giumap0** [manuelcoppotelli/beamer-roma-theme#2]
Hello.
I am trying to use your files to create a presentation for my thesis in latex but it apparently doesn't work.
Can you help me?
it shows me this when I try to compile
 PDF Rendering Error Something went wrong while rendering this PDF.
thank you

**Comment by tjzjp** [comment]
I met the same problem, have you fixed it?

**Comment by andreabac3** [comment]
The naive (and fastest) solution is put all .sty located in the subfolder of the themes folder into the root dir.
I have created a new pull request to fix this incompatibility issue.
You can use the fixed version on overleaf at https://www.overleaf.com/read/rkjvzctxsyvt

**Comment by manuelcoppotelli** [comment]
Fixed by PR #3

**Comment by aminnazari91** [comment]
SOLUTION- Open IDM(Internet Download Manager) >Downloads >Options >General > Edit(customize IDM download panels in browser) > Turn on (Don’t capture downloads from web players automatically.) OK

**Comment by KingPsychopath** [comment]
> SOLUTION- Open IDM(Internet Download Manager) >Downloads >Options >General > Edit(customize IDM download panels in browser) > Turn on (Don’t capture downloads from web players automatically.) OK

Thanks
